rm DC_collect_data.e* 
rm DC_collect_data.o* 
rm DC_single.e*
rm DC_single.o*
rm DC_single2.o*
rm DC_single2.e*
rm DC_phase104.e*
rm DC_phase104.o*
rm DC_phase107.e*
rm DC_phase107.o*
rm DC_phase112.e*
rm DC_phase112.o*
